[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mana"
version = "0.0.1"
description = "Simplified MTG engine and RL env (starter)"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
dev = [
"pytest>=8.0",
]